### ISSUE TITLE
Laralerts stopped rendering after upgrade to 4.0.0

### ISSUE THREAD

**Issue by winkbrace** [DarkGhostHunter/Laralerts#14]
![Screenshot 2020-02-21 at 15 11 09](https://user-images.githubusercontent.com/1883930/75041251-7f076f80-54bc-11ea-9585-0a240dc2cc76.png)

The view is being rendered by the `@alerts` blade directive, but could it be that the `aler` view parameter is misnamed?

**Comment by winkbrace** [comment]
Hmm hold on, downgrading to 3.0 didn't solve the issue.  Maybe it's something else on my end...

**Comment by DarkGhostHunter** [comment]
The [`alerts` view](https://github.com/DarkGhostHunter/Laralerts/blob/master/resources/views/alerts.blade.php) should receive the `$alerts` variable. It seems your app decided to chew up the last two letters.

**Comment by winkbrace** [comment]
Oops, sorry for abandoning this. We haven't been able to resolve it and are using a fork for now.

**Comment by DarkGhostHunter** [comment]
No problem. If you know what's it is happening, please post it for future reference.
